import type { ScrollCard } from "@/entities/heroPageScrollCards/model/types";

export const cardsMock: ScrollCard[] = [
    {
        image: "/images/wine1.png",
        scrollFrom: 1000,
        scrollTo: 2000,
        horOffset: -200,
        vertOffset: 200,
        imageHorOffset: 50,
        imageVertOffset: -100,
        side: "left",
        title: "Вино, которое пишет историю",
        body: "Каждая бутылка — это винтаж из частных коллекций, доступный лишь единицам.",
    },
    {
        image: "/images/wine3.png",
        scrollFrom: 2000,
        scrollTo: 3000,
        horOffset: 220,
        vertOffset: 240,
        imageHorOffset: -70,
        imageVertOffset: -80,
        side: "right",
        title: "Только то, что скрыто от большинства",
        body: "Эксклюзивные партии из старейших шато мира, подтверждённые сертификатами и хранение в наших подвалах с момента розлива.",
    },
    {
        image: "/images/wine2.png",
        scrollFrom: 3000,
        scrollTo: 4000,
        horOffset: -210,
        vertOffset: 280,
        imageHorOffset: 50,
        imageVertOffset: -100,
        side: "left",
        title: "Вкус, который нельзя забыть",
        body: "Подарите себе или близкому человеку бутылку элитного вина, которую можно будет открыть только через несколько лет.",
    },
    {
        image: "/images/wine4.png",
        scrollFrom: 4000,
        scrollTo: 5000,
        horOffset: 210,
        vertOffset: 330,
        imageHorOffset: -90,
        imageVertOffset: -100,
        side: "right",
        title: "Элитное вино — это не просто напиток",
        body: "Это искусство, которое можно попробовать. Мы предлагаем вам стать частью этой истории.",
    },
    {
        image: "/images/wine5.png",
        scrollFrom: 5000,
        scrollTo: 6000,
        horOffset: -250,
        vertOffset: 380,
        imageHorOffset: 50,
        imageVertOffset: -130,
        side: "left",
        title: "Только лучшее из лучших",
        body: "Мы тщательно отбираем каждую бутылку, чтобы предложить вам только самые изысканные вина со всего мира.",
    },
]